"""added user passwords

Revision ID: 063cf11c3497
Revises:
Create Date: 2023-09-11 23:13:06.497194

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "063cf11c3497"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
