"""added user passwords to aws models

Revision ID: fa0b7c5c2637
Revises: 063cf11c3497
Create Date: 2023-09-11 23:19:49.080680

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa0b7c5c2637"
down_revision: Union[str, None] = "063cf11c3497"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True))
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=100), nullable=True)
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", mysql.VARCHAR(length=50), nullable=True))
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
